CREATE VIEW VW_ListaAlugueisV1

AS

SELECT

	ALUGUEL.ALCODALULOK AS ALCODALULOK,										
	ATENDENTE.ATIDATLOK AS ATIDATLOK,										
	CLIENTE.CLNOMELOK AS CLNOMELOK, 
	CLIENTE.CLCPFLOK AS CLCPFLOK,
	LOCADOR.LCRZSLOK AS LCRZSLOK, 
	LOCADOR.LCPFPJLOK AS LCPFPJLOK,		
	VEICULO.VCMARCALOK AS VCMARCALOK, 
	VEICULO.VCMODELOK AS VCMODELOK,
	VEICULO.VCPLACALOK AS VCPLACALOK,	
	ALUGUEL.ALENDATENLOK AS ALENDATENLOK, 
	ALUGUEL.ALENDENTRLOK AS ALENDENTRLOK,
	ALUGUEL.ALDTINILOK AS ALDTINILOK,
	ALUGUEL.ALDTFIMLOK AS ALDTFIMLOK,
	ALUGUEL.ALVLRTTLOK AS ALVLRTTLOK,	
	ALUGUEL.ALSITLOK AS ALSITLOK

FROM TBALUGUELLOK AS ALUGUEL
	
	INNER JOIN TBATNDLOK AS ATENDENTE ON ALUGUEL.ALCODATELOK = ATENDENTE.ATIDATLOK
	INNER JOIN TBCLIENTLOK AS CLIENTE ON ALUGUEL.ALCODCLILOK = CLIENTE.CLIDCLLOK
	INNER JOIN TBLOCLOK AS LOCADOR ON ALUGUEL.ALCODLOCLOK = LOCADOR.LCIDLOCLOK
	INNER JOIN TBVEICLOK AS VEICULO ON ALUGUEL.ALCODVEILOK = VEICULO.VCIDLOK

WHERE ALUGUEL.ALSITLOK = 'A'