USE DB_LOKANDO

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBUSULOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBUSULOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBUSULOK(	
		USIDUSU int IDENTITY NOT NULL,
		USEMAILLOK varchar(100) NOT NULL,
	    USSENHALOK varchar(100) NOT NULL,    
		USTPUSULOK char(1) NOT NULL, 
	    USSITLOK char(1) NOT NULL,
	    USUHRREG datetime NOT NULL,		
		CONSTRAINT TBUSULOK_PK PRIMARY KEY CLUSTERED (USIDUSU),		
	    CONSTRAINT TBUSULOK_CK_01 CHECK (USSITLOK = 'A' OR USSITLOK = 'I' OR USSITLOK = 'B') -- Ativo, Inativo, Bloqueado	
	)
	PRINT 'Criada a tabela TBUSULOK.'
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBATNDLOK')
BEGIN	
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBATNDLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBATNDLOK(	
		ATIDATLOK int IDENTITY NOT NULL,
		ATUSUATLOK int NOT NULL,	
		ATNOMELOK varchar(100) NOT NULL,    	   
	    ATEMAILLOK varchar(100) NOT NULL,		
		ATSITATLOK char(1) NOT NULL, 	
	    ATHRREG datetime NOT NULL,		
		CONSTRAINT TBATNDLOK_PK PRIMARY KEY CLUSTERED (ATIDATLOK),
		CONSTRAINT TBATNDLOK_FK_01 FOREIGN KEY (ATUSUATLOK) REFERENCES TBUSULOK(USIDUSU),		
		CONSTRAINT TBATNDLOK_CK_01 CHECK (ATSITATLOK = 'A' OR ATSITATLOK = 'I' OR ATSITATLOK = 'B') -- Ativo, Inativo, Bloqueado	
	)
	PRINT 'Criada a tabela TBATNDLOK' 
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBCLIENTLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBCLIENTLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBCLIENTLOK(	
		CLIDCLLOK int IDENTITY NOT NULL,
		CLCODUSLOK int NOT NULL,	
		CLNOMELOK varchar(100) NOT NULL,
		CLHABILLOK varchar(100) NOT NULL,    	   
	    CLCPFLOK varchar(14) NOT NULL,
		CLRGLOK varchar(100) NOT NULL,
		CLNASCLOK datetime NOT NULL,
		CLEMAILLOK varchar (100),
		CLNMLOK varchar(100) NULL,
		CLLOGLOK varchar(100) NOT NULL,
		CLBAIRROLOK varchar(100) NOT NULL,
		CLCIDLOK varchar(100) NOT NULL,
		CLUFLOK varchar(2) NOT NULL,
		CLCEPLOK varchar(9) NULL,			
		CLSITLOK char(1) NOT NULL,
	    CLHRREG datetime NOT NULL,		
		CONSTRAINT TBCLIENTLOK_PK PRIMARY KEY CLUSTERED (CLIDCLLOK),
		CONSTRAINT TBCLIENTLOK_FK_01 FOREIGN KEY (CLCODUSLOK) REFERENCES TBUSULOK(USIDUSU),	
		CONSTRAINT TBCLIENTLOK_CK_01 CHECK (CLSITLOK = 'A' OR CLSITLOK = 'I' OR CLSITLOK = 'B') -- Ativo, Inativo, Bloqueado		
	)
	PRINT 'Criada a tabela TBCLIENTLOK' 
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBLOCLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBLOCLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBLOCLOK(
		LCIDLOCLOK int IDENTITY NOT NULL,	
		LCCODUSLOK int NOT NULL,
		LCEMAILLOK varchar (100) NOT NULL,
		LCRZSLOK varchar(100) NOT NULL,
	    LCFANTLOK varchar(100) NOT NULL,	 
	    LCPFPJLOK varchar(18) NOT NULL,
		LCNMLOK varchar(100) NULL,
		LCLOGLOK varchar(100) NOT NULL,
		LCBAIRROLOK varchar(100) NOT NULL,
		LCCIDLOK varchar(100) NOT NULL,
		LCUFLOK varchar(2) NOT NULL,
		LCCEPLOK varchar(9) NULL,		    
		LCSITLOK char(1) NOT NULL,	
	    LCUHRREG datetime NOT NULL,	
		CONSTRAINT TBLOCLOK_PK PRIMARY KEY CLUSTERED (LCIDLOCLOK),
		CONSTRAINT TBLOCLOK_FK_01 FOREIGN KEY (LCCODUSLOK) REFERENCES TBUSULOK(USIDUSU),		
		CONSTRAINT TBLOCLOK_CK_01 CHECK (LCSITLOK = 'A' OR LCSITLOK = 'I' OR LCSITLOK = 'B') -- Ativo, Inativo, Bloqueado		
	)
	PRINT 'Criada a tabela TBLOCLOK.'
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBVEICLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBVEICLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBVEICLOK(
		VCIDLOK int IDENTITY NOT NULL,	
		VCCODLCDLOK int NOT NULL,
		VCTPLOK varchar(100) NOT NULL,    
	    VCMARCALOK varchar(100) NOT NULL,
	    VCMODELOK varchar(100) NOT NULL,
	    VCPLACALOK varchar(7) NOT NULL,
	    VCRNVLOK varchar(100) NOT NULL,
	    VCCOMBLOK varchar(100) NOT NULL,
	    VCCORLOK varchar(100) NOT NULL,    
		VCANOLOK varchar(4) NOT NULL,
	    VCVLRDIA decimal(9,2) NOT NULL,    	    
	    VCSITLOK char(1) NOT NULL,
		VCHRREGLOK datetime NOT NULL,		
		CONSTRAINT TBVEICLOK_PK PRIMARY KEY CLUSTERED (VCIDLOK),    
	    CONSTRAINT TBVEICLOK_FK_01 FOREIGN KEY (VCCODLCDLOK) REFERENCES TBLOCLOK(LCIDLOCLOK), 
	    CONSTRAINT TBVEICLOK_CK_01 CHECK (LEN(VCPLACALOK) = 7),
		CONSTRAINT TBVEICLOK_CK_02 CHECK (VCSITLOK = 'D' OR VCSITLOK = 'L' OR VCSITLOK = 'B' OR VCSITLOK = 'I')	-- Disponível, Locado, Bloqueado, Inativo
	)
	PRINT 'Criada a tabela TBVEICLOK.'
END

IF EXISTS (Select O.name From SYSOBJECTS as O with(nolock) where name = 'TBALUGUELLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBALUGUELLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBALUGUELLOK(	
		ALCODALULOK int IDENTITY NOT NULL,
		ALCODATELOK int NOT NULL,
		ALCODCLILOK int NOT NULL,
	    ALCODLOCLOK int NOT NULL,    
		ALCODVEILOK int NOT NULL, 
		ALENDATENLOK varchar(100) NOT NULL,
		ALENDENTRLOK varchar(100) NOT NULL,
	    ALDTINILOK datetime NOT NULL,
		ALDTFIMLOK datetime NOT NULL,
		ALVLRTTLOK decimal(9,2) NOT NULL,
		ALSITLOK char(1) NOT NULL,
	    ALHRREG  datetime NOT NULL,				
		CONSTRAINT TBALUGUELLOK_PK PRIMARY KEY CLUSTERED (ALCODALULOK),		
		CONSTRAINT TBALUGUELLOK_FK_01 FOREIGN KEY (ALCODATELOK) REFERENCES TBATNDLOK(ATIDATLOK),    
		CONSTRAINT TBALUGUELLOK_FK_02 FOREIGN KEY (ALCODCLILOK) REFERENCES TBCLIENTLOK(CLIDCLLOK), 
		CONSTRAINT TBALUGUELLOK_FK_03 FOREIGN KEY (ALCODLOCLOK) REFERENCES TBLOCLOK(LCIDLOCLOK),
		CONSTRAINT TBALUGUELLOK_FK_04 FOREIGN KEY (ALCODVEILOK) REFERENCES TBVEICLOK(VCIDLOK),
	    CONSTRAINT TBALUGUELLOK_CK_01 CHECK (ALSITLOK = 'A' OR ALSITLOK = 'I') -- Ativo, Inativo	
	)
	PRINT 'Criada a tabela TBALUGUELLOK.'	
END

