USE DB_LOKANDO

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBUSULOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBUSULOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBUSULOK(	
		USIDUSU int IDENTITY NOT NULL,
		USEMAILLOK varchar(100) NOT NULL,
	    USSENHALOK varchar(100) NOT NULL,    
	    USSITLOK char(1) NOT NULL,
	    USUHRREG datetime NOT NULL,		
		CONSTRAINT TBUSULOK_PK PRIMARY KEY CLUSTERED (USIDUSU),		
	    CONSTRAINT TBUSULOK_CK_01 CHECK (USSITLOK = 'A' OR USSITLOK = 'I' OR USSITLOK = 'B') -- Ativo, Inativo, Bloqueado	
	)
	PRINT 'Criada a tabela TBUSULOK.'
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBTOKENLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBTOKENLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBTOKENLOK(
		TOKENLOK varchar(100) NOT NULL,
	    TKDTGERALOK datetime NULL,
	    TKORIGEMLOK varchar(100) NULL,
	    TKDESTINOLOK varchar(100) NULL,
		TKDTUTILLOK datetime NULL,	
		TKUTILUSULOK int NULL,	
		TKRTNLOK varchar(8000) NULL,
		TKVALIDLOK datetime NULL,	
		CONSTRAINT TBTOKENLOK_PK PRIMARY KEY CLUSTERED (TOKENLOK),
		CONSTRAINT TBTOKENLOK_FK_01 FOREIGN KEY (TKUTILUSULOK) REFERENCES TBUSULOK(USIDUSU)		
	)
	PRINT 'Criada a tabela TBTOKENLOK.' 
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBATNDLOK')
BEGIN	
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBATNDLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBATNDLOK(	
		ATIDATLOK int IDENTITY NOT NULL,
		ATUSUATLOK int NOT NULL,	
		ATNOMELOK varchar(100) NOT NULL,    	   
	    ATEMAILLOK varchar(100) NOT NULL,		
		ATSITATLOK char(1) NOT NULL, 	
	    ATHRREG datetime NOT NULL,		
		CONSTRAINT TBATNDLOK_PK PRIMARY KEY CLUSTERED (ATIDATLOK),
		CONSTRAINT TBATNDLOK_FK_01 FOREIGN KEY (ATUSUATLOK) REFERENCES TBUSULOK(USIDUSU),		
		CONSTRAINT TBATNDLOK_CK_01 CHECK (ATSITATLOK = 'A' OR ATSITATLOK = 'I' OR ATSITATLOK = 'B') -- Ativo, Inativo, Bloqueado	
	)
	PRINT 'Criada a tabela TBATNDLOK' 
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBCLIENTLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBCLIENTLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBCLIENTLOK(	
		CLIDCLLOK int IDENTITY NOT NULL,
		CLCODUSLOK int NOT NULL,	
		CLNOMELOK varchar(100) NOT NULL,
		CLHABILLOK varchar(100) NOT NULL,    	   
	    CLCPFLOK varchar(14) NOT NULL,
		CLRGLOK varchar(100) NOT NULL,
		CLNASCLOK datetime NOT NULL,
		CLEMAILLOK varchar (100),
		CLNMLOK varchar(100) NULL,
		CLLOGLOK varchar(100) NOT NULL,
		CLCIDLOK varchar(100) NOT NULL,
		CLUFLOK varchar(2) NOT NULL,
		CLCEPLOK varchar(9) NULL,	
		CLSITLOK char(1) NOT NULL, 	
	    CLHRREG datetime NOT NULL,		
		CONSTRAINT TBCLIENTLOK_PK PRIMARY KEY CLUSTERED (CLIDCLLOK),
		CONSTRAINT TBCLIENTLOK_FK_01 FOREIGN KEY (CLCODUSLOK) REFERENCES TBUSULOK(USIDUSU),	
		CONSTRAINT TBCLIENTLOK_CK_01 CHECK (CLSITLOK = 'A' OR CLSITLOK = 'I' OR CLSITLOK = 'B') -- Ativo, Inativo, Bloqueado		
	)
	PRINT 'Criada a tabela TBCLIENTLOK' 
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBLOCLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBLOCLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBLOCLOK(
		LCIDLOCLOK int IDENTITY NOT NULL,	
		LCCODUSLOK int NOT NULL,
		LCEMAILLOK varchar (100) NOT NULL,
		LCRZSLOK varchar(100) NOT NULL,
	    LCFANTLOK varchar(100) NOT NULL,	 
	    LCPFPJLOK varchar(18) NOT NULL,
		LCNMLOK varchar(100) NULL,
		LCLOGLOK varchar(100) NOT NULL,
		LCCIDLOK varchar(100) NOT NULL,
		LCUFLOK varchar(2) NOT NULL,
		LCCEPLOK varchar(9) NULL,	
	    LCSITLOK char(1) NOT NULL,	
	    LCUHRREG datetime NOT NULL,	
		CONSTRAINT TBLOCLOK_PK PRIMARY KEY CLUSTERED (LCIDLOCLOK),
		CONSTRAINT TBLOCLOK_FK_01 FOREIGN KEY (LCCODUSLOK) REFERENCES TBUSULOK(USIDUSU),		
		CONSTRAINT TBLOCLOK_CK_01 CHECK (LCSITLOK = 'A' OR LCSITLOK = 'I' OR LCSITLOK = 'B') -- Ativo, Inativo, Bloqueado		
	)
	PRINT 'Criada a tabela TBLOCLOK.'
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBVEICLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBVEICLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBVEICLOK(
		VCIDLOK int IDENTITY NOT NULL,	
		VCCODLCDLOK int NOT NULL,
		VCTPLOK varchar(100) NOT NULL,    
	    VCMARCALOK varchar(100) NOT NULL,
	    VCMODELOK varchar(100) NOT NULL,
	    VCPLACALOK varchar(7) NOT NULL,
	    VCRNVLOK varchar(100) NOT NULL,
	    VCCOMBLOK varchar(100) NOT NULL,
	    VCCORLOK varchar(100) NOT NULL,    
	    VCVLRDIA decimal(9,2) NOT NULL,    	    
	    VCSITLOK char(1) NOT NULL,
		VCHRREGLOK datetime NOT NULL,		
		CONSTRAINT TBVEICLOK_PK PRIMARY KEY CLUSTERED (VCIDLOK),    
	    CONSTRAINT TBVEICLOK_FK_01 FOREIGN KEY (VCCODLCDLOK) REFERENCES TBLOCLOK(LCIDLOCLOK), 
	    CONSTRAINT TBVEICLOK_CK_01 CHECK (LEN(VCPLACALOK) = 7),
		CONSTRAINT TBVEICLOK_CK_02 CHECK (VCSITLOK = 'D' OR VCSITLOK = 'L' OR VCSITLOK = 'B' OR VCSITLOK = 'I')	-- Disponível, Locado, Bloqueado, Inativo
	)
	PRINT 'Criada a tabela TBVEICLOK.'
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBORCLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBORCLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBORCLOK(
		ORNRLOK int IDENTITY NOT NULL,	
		ORIDCLLOK int NOT NULL,
		ORNMCLLOK varchar(100) NOT NULL,
		ORCPFCLLOK varchar(14) NOT NULL,
		ORNASCLOK datetime NOT NULL, 
		ORIDVEICLOK int NOT NULL, 
		ORCODLCTLOK int NOT NULL, 
		ORDTINILOK datetime NOT NULL,
		ORDTFIMLOK datetime NOT NULL,
		ORLOGRETLOK varchar(300) NOT NULL,
		ORLOGDEVLOK varchar(300) NOT NULL,
		ORVLRTLOK decimal(9,2) NOT NULL,
		ORSITORLOK char(1) NOT NULL,
		ORHRREGLOK datetime NOT NULL,	
		CONSTRAINT TBORCLOK_PK PRIMARY KEY CLUSTERED (ORNRLOK),
		CONSTRAINT TBORCLOK_FK_01 FOREIGN KEY (ORIDCLLOK) REFERENCES TBCLIENTLOK(CLIDCLLOK),
		CONSTRAINT TBORCLOK_FK_02 FOREIGN KEY (ORIDVEICLOK) REFERENCES TBVEICLOK(VCIDLOK),
		CONSTRAINT TBORCLOK_FK_03 FOREIGN KEY (ORCODLCTLOK) REFERENCES TBLOCLOK(LCIDLOCLOK), 
		CONSTRAINT TBORCLOK_CK_01 CHECK (ORSITORLOK = 'E' OR ORSITORLOK = 'P' OR ORSITORLOK = 'R')	-- (Proposra) Enviada, (Tornou-se) Pedido, (Orçamento Foi) Rejeitado
	)
	PRINT 'Criada a tabela TBORCLOK.'
END

IF EXISTS (Select O.name From SYSOBJECTS O with(nolock) where name = 'TBPEDLOK')
BEGIN			
	PRINT 'Tabela já existe na base de dados. Não é possível recriar a tabela TBPEDLOK.'	
END
ELSE
BEGIN
	CREATE TABLE TBPEDLOK(
		PDNRLOK int IDENTITY NOT NULL,	
		PDCODCLLOK int NOT NULL,
		PDNMCLLOK varchar(100) NOT NULL, 
		PDHBCLLOK varchar(100) NOT NULL,   
		PDCPFCLLOK varchar(14) NOT NULL,    
		PDCODLCTLOK int NOT NULL,      
		PDNMLCTLOK varchar(100) NOT NULL, 
		PDCODVCLOK int NOT NULL,      
		PDVCPLCLOK varchar(7) NOT NULL, 
		PDNRORCLOK int NOT NULL,
		PDVLRTLOK decimal(9,2) NOT NULL,
		PDSITPEDLOK char(1) NOT NULL,    
		PDHRREGLOK datetime NOT NULL,	
		CONSTRAINT TBPEDLOK_PK PRIMARY KEY CLUSTERED (PDNRLOK),
		CONSTRAINT TBPEDLOK_FK_01 FOREIGN KEY (PDCODCLLOK) REFERENCES TBCLIENTLOK(CLIDCLLOK),    
		CONSTRAINT TBPEDLOK_FK_02 FOREIGN KEY (PDCODLCTLOK) REFERENCES TBLOCLOK(LCIDLOCLOK), 
		CONSTRAINT TBPEDLOK_FK_03 FOREIGN KEY (PDCODVCLOK) REFERENCES TBVEICLOK(VCIDLOK),
		CONSTRAINT TBPEDLOK_FK_04 FOREIGN KEY (PDNRORCLOK) REFERENCES TBORCLOK(ORNRLOK),    
		CONSTRAINT TBPEDLOK_CK_01 CHECK (LEN(PDVCPLCLOK) = 7),
		CONSTRAINT TBPEDLOK_CK_02 CHECK (PDSITPEDLOK = 'F' OR PDSITPEDLOK = 'C' OR PDSITPEDLOK = 'A')	-- Finalizado, Cancelado, (Em) Andamento
	)
	PRINT 'Criada a tabela TBPEDLOK.'
END

